### PR TITLE
Update Makefile to run `asdf install` (plus a couple other small improvements)

### LINKED ISSUE #13: Add `asdf install` to the automation steps
If the version installed in the build harness does not exactly match what we have in the .tool-versions file the pipeline will currently fail. If we were to add `asdf install` as a pre-step the job would first install the requisite version(s) that we want and continue running. This is inefficient since that installation will happen in every pipeline run but it is better than a failing test that blocks us when it doesn't have to.

### PR DESCRIPTION
**Pull request by RothAndrew**
Fixes #13

### CODE REVIEW

**Comment by RothAndrew** [comment]
Gonna go install `adr-tools` on build harness. I'd rather do that than take it out of the .tool-versions file

**Review by ntwkninja — APPROVED** [review]
LGTM!

**Pull request merged**
