### PR TITLE
Renovate more ASDF things

### PR DESCRIPTION
**Pull request by RothAndrew**
Renovate doesn't support all the different ASDF plugins that are listed in .tool-versions. This tells Renovate how to check for the ones that it doesn't support natively yet.

Copied from (and tested in) [here](https://github.com/defenseunicorns/delivery-aws-iac)

### CODE REVIEW

**Comment by RothAndrew** [comment]
This will help keep in sync with the tools that are installed in the build harness, so that the pipelines don't have to keep installing tools on every run. If they stay in sync with the build harness, the `asdf install` command will just do nothing.

**Comment by RothAndrew** [comment]
The one for Checkov will throw an error currently, but Renovate is working on fixing it. See https://github.com/renovatebot/renovate/discussions/21962

**Comment by RothAndrew** [comment]
I have a PR in to add these plugins so that renovate supports them natively. Once that is merged and released this code can be deleted.

https://github.com/renovatebot/renovate/pull/21942

**Review by wirewc — APPROVED** [review]
LGTM, thanks Andy!

**Pull request merged**
