### PR TITLE
EXPERIMENT

### PR DESCRIPTION
**Pull request by lucasrod16**
***JUST AN EXPERIMENT***

### CODE REVIEW

**Comment by RothAndrew** [comment]
You won't see any immediate difference here. The Slash Command Dispatch uses the workflow configuration from the "main" branch only.

There are a couple of different ways to test changes to it. The one I use most often is to fork the repo, make the changes in main in the fork, and recreate the changes in the primary repo once I am satisfied they are going to do what I want them to do.

**Comment by RothAndrew** [comment]
It works this way because when workflow runs happen in the context of the "main" branch, full access to GitHub actions secrets are granted

**Comment by bdfinst** [comment]
> It works this way because when workflow runs happen in the context of the "main" branch, full access to GitHub actions secrets are granted

Yeah, we are running an experiment. We came up with a lighter option to prevent needing to set up creds just for this experiment,

**Review by bdfinst — APPROVED** [review]
Do it

**Pull request merged**
