### PR TITLE
Document decisions pertaining to testing as ADRs

### PR DESCRIPTION
**Pull request by RothAndrew**
Add 2 ADRs:
- One relating to the use of the Slash Command Dispatch
- One relating to the use of a docker container as a wrapper around testing logic.

### CODE REVIEW

**Comment by RothAndrew** [comment]
@ntwkninja would like your input as well.

**Comment by RothAndrew** [comment]
Note: I'm not looking to get everyone to agree to these decisions. I'm documenting the decisions that were already made when this module was owned by Delivery. Product is welcome to amend these decisions if they want to, but they should be documented as decisions that were made, and were later amended, so that a record of what took place can be kept.

**Comment by RothAndrew** [comment]
@ntwkninja please review this and, if you agree that it properly documents the decisions that were made by Delivery around testing IaC modules, give it your approval and merge it, to reflect the decisions that were made previously.

Product may then amend the decisions if they want to, by creating new ADRs that amend the previous ones.

The `adr-tools` tool has easy capability to create ADRs that amend previous ADRs, that will automatically go into the previous adr and add an "amended by" statement with a link to the new ADR.

**Review by ntwkninja — APPROVED** [review]
previously discussed and agreed upon; merging as an indicator of where things are today and why

this is not intended to dissuade future improvements, innovation or changes. This is merely documenting why.

**Comment by wirewc** [comment]
I'm late to this but LGTM, thanks @RothAndrew!

**Review by bdfinst — APPROVED** [review]
LGTM

**Comment by austenbryan** [comment]
👍

**Pull request merged**
