### PR TITLE
Refactor test workflow

### PR DESCRIPTION
**Pull request by lucasrod16**
Closes https://github.com/defenseunicorns/uds/issues/46, https://github.com/defenseunicorns/uds/issues/45, https://github.com/defenseunicorns/uds/issues/48

The goal of this PR is to simplify how tests are run in CI.

What this PR does:

- Runs tests on every commit pushed to a branch associated with a Pull Request
- Runs tests on every commit pushed to `main` branch. So when a Pull Request is merged
- Removes logic related to running tests via comments/commands in a Pull Request
- Removes use of containers used in the test workflow

### CODE REVIEW

**Comment by RothAndrew** [comment]
This won't work for any open source contributors. PRs from forks don't get access to secrets.

It will also cause the tests to trigger on every push to the branch, which, when each test run costs real money, can add up quickly.

It is a very well established pattern to manually trigger tests of Infrastructure as Code rather than let them run manually.

**Comment by lucasrod16** [comment]
@RothAndrew 

> This won't work for any open source contributors. PRs from forks don't get access to secrets.

Contributors who fork can create their own secrets for AWS credentials. That could be a process documented in the contributing guide.

> It will also cause the tests to trigger on every push to the branch, which, when each test run costs real money, can add up quickly.

 Costs for spinning up and tearing down an ephemeral s3 bucket and dynamo db table shouldn't be that much. If this is a real concern, calculating the actual cost and running it by the people who make budget-related decisions should be consulted. Not engineers doing guess work.

> It is a very well established pattern to manually trigger tests of Infrastructure as Code rather than let them run automatically.

There are a lot of well established patterns in software such as manual testing, change advisory boards, mandatory daily scrums, etc. Being well established has no relation to quality.

**Comment by lucasrod16** [comment]
> > @RothAndrew
> > > This won't work for any open source contributors. PRs from forks don't get access to secrets.
> > 
> > 
> > Contributors who fork can create their own secrets for AWS credentials. That could be a process documented in the contributing guide.
> > > It will also cause the tests to trigger on every push to the branch, which, when each test run costs real money, can add up quickly.
> > 
> > 
> > Costs for spinning up and tearing down an ephemeral s3 bucket and dynamo db table shouldn't be that much. If this is a real concern, calculating the actual cost and running it by the people who make budget-related decisions should be consulted. Not engineers doing guess work.
> > > It is a very well established pattern to manually trigger tests of Infrastructure as Code rather than let them run automatically.
> > 
> > 
> > There are a lot of well established patterns in software such as manual testing, change advisory boards, mandatory daily scrums, etc. Being well established has no relation to quality.
> 
> Happy to let you guys dive down the rabbit hole of how to effectively test IaC modules. My word of caution is that that rabbit hole is already well traveled, and there are a lot of things that have been learned in the process.

The actual Terratest tests haven't changed. Just the way CI is orchestrated to run them. So it's not like we're scrapping everything and starting from scratch.

**Comment by RothAndrew** [comment]
> > > @RothAndrew
> > > > This won't work for any open source contributors. PRs from forks don't get access to secrets.
> > > 
> > > 
> > > Contributors who fork can create their own secrets for AWS credentials. That could be a process documented in the contributing guide.
> > > > It will also cause the tests to trigger on every push to the branch, which, when each test run costs real money, can add up quickly.
> > > 
> > > 
> > > Costs for spinning up and tearing down an ephemeral s3 bucket and dynamo db table shouldn't be that much. If this is a real concern, calculating the actual cost and running it by the people who make budget-related decisions should be consulted. Not engineers doing guess work.
> > > > It is a very well established pattern to manually trigger tests of Infrastructure as Code rather than let them run automatically.
> > > 
> > > 
> > > There are a lot of well established patterns in software such as manual testing, change advisory boards, mandatory daily scrums, etc. Being well established has no relation to quality.
> > 
> > 
> > Happy to let you guys dive down the rabbit hole of how to effectively test IaC modules. My word of caution is that that rabbit hole is already well traveled, and there are a lot of things that have been learned in the process.
> 
> The actual Terratest tests haven't changed. Just the way CI is orchestrated to run them. So it's not like we're scrapping everything and starting from scratch.

Copy that. You're right, you aren't scrapping the tests, just scrapping everything about the way the tests are run and starting from scratch.

Which you guys have every right to do. [I'm recommending that you don't](https://en.wikipedia.org/wiki/Not_invented_here), but this is your ball game.

Let me know if I can be of any assistance. I have roughly 3 years of experience as a core contributor to CloudPosse's library of hundreds of Terraform modules.

**Comment by lucasrod16** [comment]
> Copy that. You're right, you aren't scrapping the tests, just scrapping everything about the way the tests are run and starting from scratch.
> 
> Which you guys have every right to do. [I'm recommending that you don't](https://en.wikipedia.org/wiki/Not_invented_here), but this is your ball game.
> 
> Let me know if I can be of any assistance. I have roughly 3 years of experience as a core contributor to CloudPosse's library of hundreds of Terraform modules.

The tests are written Go. It's not complicated to run Go tests. It's `go test`. You can create straw-man arguments and use accusatory language if you'd like, but it doesn't help anybody. The goal of this PR isn't to reinvent the wheel. It's to simplify things.

Also, we may not even use Terraform for infrastructure long-term, so I wouldn't get too wrapped up in Terraform-specific implementation details.

This PR is open for review. There are no guarantees or consensus yet.

**Comment by bdfinst** [comment]
After getting clarification from @RothAndrew we should take another approach here.

**Pull request closed without merging**
