### PR TITLE
Add composite actions for setup steps to run tests

### PR DESCRIPTION
**Pull request by lucasrod16**
Relates to https://github.com/defenseunicorns/uds/issues/46

### CODE REVIEW

**Comment by wirewc** [comment]
@lucasrod16 is this a branch in active development for testing or is this ready to be merged?

**Comment by lucasrod16** [comment]
> @lucasrod16 is this a branch in active development for testing or is this ready to be merged?

@wirewc just marked the PR as draft. Still working on this

**Review by bdfinst — APPROVED** [review]
LGTM

**Pull request merged**
